

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class Button;
                ref class TextBlock;
                ref class ComboBox;
                ref class ToggleSwitch;
                ref class TextBox;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace Yatzy
{
    partial ref class Einstellungen : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
        private: ::Windows::UI::Xaml::Controls::Button^ buttonReset;
        private: ::Windows::UI::Xaml::Controls::Button^ buttonOK;
        private: ::Windows::UI::Xaml::Controls::Grid^ gridName;
        private: ::Windows::UI::Xaml::Controls::Grid^ gridVorschau;
        private: ::Windows::UI::Xaml::Controls::Grid^ gridWürfel;
        private: ::Windows::UI::Xaml::Controls::Grid^ gridHintergrund;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textHintergrund;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ ComboBoxFarbeBackground;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textWürfel;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ ComboBoxWürfel;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textVorschau;
        private: ::Windows::UI::Xaml::Controls::ToggleSwitch^ ToggleVorschau;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textName;
        private: ::Windows::UI::Xaml::Controls::TextBox^ TextBoxName;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textÜberschrift;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ rectÜberschrift;
    };
}

