

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Image;
                ref class Grid;
                ref class Border;
                ref class TextBlock;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace Yatzy
{
    partial ref class Erfolge : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Image^ ImageWillkommenWeiß;
        private: ::Windows::UI::Xaml::Controls::Image^ ImageSiegerWeiß;
        private: ::Windows::UI::Xaml::Controls::Image^ ImagePerfektWeiß;
        private: ::Windows::UI::Xaml::Controls::Image^ ImageAnfängerWeiß;
        private: ::Windows::UI::Xaml::Controls::Image^ ImageGelegenWeiß;
        private: ::Windows::UI::Xaml::Controls::Image^ ImageFortgWeiß;
        private: ::Windows::UI::Xaml::Controls::Image^ ImageProfiWeiß;
        private: ::Windows::UI::Xaml::Controls::Image^ ImageMeisterWeiß;
        private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
        private: ::Windows::UI::Xaml::Controls::Grid^ gridMeister;
        private: ::Windows::UI::Xaml::Controls::Border^ borderMeister;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text1Meister;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text2Meister;
        private: ::Windows::UI::Xaml::Controls::Image^ imageMeister;
        private: ::Windows::UI::Xaml::Controls::Grid^ gridProfi;
        private: ::Windows::UI::Xaml::Controls::Border^ borderProfi;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text1Profi;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text2Profi;
        private: ::Windows::UI::Xaml::Controls::Image^ imageProfi;
        private: ::Windows::UI::Xaml::Controls::Grid^ gridFortg;
        private: ::Windows::UI::Xaml::Controls::Border^ borderFortg;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text1Fortg;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text2Fortg;
        private: ::Windows::UI::Xaml::Controls::Image^ imageFortg;
        private: ::Windows::UI::Xaml::Controls::Grid^ gridGeleg;
        private: ::Windows::UI::Xaml::Controls::Border^ borderGeleg;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text1Geleg;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text2Geleg;
        private: ::Windows::UI::Xaml::Controls::Image^ imageGeleg;
        private: ::Windows::UI::Xaml::Controls::Grid^ gridAnf;
        private: ::Windows::UI::Xaml::Controls::Border^ borderAnf;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text1Anf;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text2Anf;
        private: ::Windows::UI::Xaml::Controls::Image^ imageAnf;
        private: ::Windows::UI::Xaml::Controls::Grid^ gridPerf;
        private: ::Windows::UI::Xaml::Controls::Border^ borderPerf;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text1Perf;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text2Perf;
        private: ::Windows::UI::Xaml::Controls::Image^ imagePerf;
        private: ::Windows::UI::Xaml::Controls::Grid^ gridSieger;
        private: ::Windows::UI::Xaml::Controls::Border^ borderSieger;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text1Sieger;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text2Sieger;
        private: ::Windows::UI::Xaml::Controls::Image^ imageSieger;
        private: ::Windows::UI::Xaml::Controls::Grid^ gridWill;
        private: ::Windows::UI::Xaml::Controls::Border^ borderWill;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text1Will;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ text2Will;
        private: ::Windows::UI::Xaml::Controls::Image^ imageWill;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textÜberschrift;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ rectÜberschrift;
    };
}

