

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "Erfolge.xaml.h"




void ::Yatzy::Erfolge::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///Erfolge.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///Erfolge.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the Image named 'ImageWillkommenWeiß'
    ImageWillkommenWeiß = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ImageWillkommenWeiß"));
    // Get the Image named 'ImageSiegerWeiß'
    ImageSiegerWeiß = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ImageSiegerWeiß"));
    // Get the Image named 'ImagePerfektWeiß'
    ImagePerfektWeiß = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ImagePerfektWeiß"));
    // Get the Image named 'ImageAnfängerWeiß'
    ImageAnfängerWeiß = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ImageAnfängerWeiß"));
    // Get the Image named 'ImageGelegenWeiß'
    ImageGelegenWeiß = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ImageGelegenWeiß"));
    // Get the Image named 'ImageFortgWeiß'
    ImageFortgWeiß = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ImageFortgWeiß"));
    // Get the Image named 'ImageProfiWeiß'
    ImageProfiWeiß = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ImageProfiWeiß"));
    // Get the Image named 'ImageMeisterWeiß'
    ImageMeisterWeiß = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ImageMeisterWeiß"));
    // Get the Grid named 'LayoutRoot'
    LayoutRoot = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"LayoutRoot"));
    // Get the Grid named 'gridMeister'
    gridMeister = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"gridMeister"));
    // Get the Border named 'borderMeister'
    borderMeister = safe_cast<::Windows::UI::Xaml::Controls::Border^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"borderMeister"));
    // Get the TextBlock named 'text1Meister'
    text1Meister = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text1Meister"));
    // Get the TextBlock named 'text2Meister'
    text2Meister = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text2Meister"));
    // Get the Image named 'imageMeister'
    imageMeister = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"imageMeister"));
    // Get the Grid named 'gridProfi'
    gridProfi = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"gridProfi"));
    // Get the Border named 'borderProfi'
    borderProfi = safe_cast<::Windows::UI::Xaml::Controls::Border^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"borderProfi"));
    // Get the TextBlock named 'text1Profi'
    text1Profi = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text1Profi"));
    // Get the TextBlock named 'text2Profi'
    text2Profi = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text2Profi"));
    // Get the Image named 'imageProfi'
    imageProfi = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"imageProfi"));
    // Get the Grid named 'gridFortg'
    gridFortg = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"gridFortg"));
    // Get the Border named 'borderFortg'
    borderFortg = safe_cast<::Windows::UI::Xaml::Controls::Border^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"borderFortg"));
    // Get the TextBlock named 'text1Fortg'
    text1Fortg = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text1Fortg"));
    // Get the TextBlock named 'text2Fortg'
    text2Fortg = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text2Fortg"));
    // Get the Image named 'imageFortg'
    imageFortg = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"imageFortg"));
    // Get the Grid named 'gridGeleg'
    gridGeleg = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"gridGeleg"));
    // Get the Border named 'borderGeleg'
    borderGeleg = safe_cast<::Windows::UI::Xaml::Controls::Border^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"borderGeleg"));
    // Get the TextBlock named 'text1Geleg'
    text1Geleg = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text1Geleg"));
    // Get the TextBlock named 'text2Geleg'
    text2Geleg = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text2Geleg"));
    // Get the Image named 'imageGeleg'
    imageGeleg = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"imageGeleg"));
    // Get the Grid named 'gridAnf'
    gridAnf = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"gridAnf"));
    // Get the Border named 'borderAnf'
    borderAnf = safe_cast<::Windows::UI::Xaml::Controls::Border^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"borderAnf"));
    // Get the TextBlock named 'text1Anf'
    text1Anf = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text1Anf"));
    // Get the TextBlock named 'text2Anf'
    text2Anf = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text2Anf"));
    // Get the Image named 'imageAnf'
    imageAnf = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"imageAnf"));
    // Get the Grid named 'gridPerf'
    gridPerf = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"gridPerf"));
    // Get the Border named 'borderPerf'
    borderPerf = safe_cast<::Windows::UI::Xaml::Controls::Border^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"borderPerf"));
    // Get the TextBlock named 'text1Perf'
    text1Perf = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text1Perf"));
    // Get the TextBlock named 'text2Perf'
    text2Perf = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text2Perf"));
    // Get the Image named 'imagePerf'
    imagePerf = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"imagePerf"));
    // Get the Grid named 'gridSieger'
    gridSieger = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"gridSieger"));
    // Get the Border named 'borderSieger'
    borderSieger = safe_cast<::Windows::UI::Xaml::Controls::Border^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"borderSieger"));
    // Get the TextBlock named 'text1Sieger'
    text1Sieger = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text1Sieger"));
    // Get the TextBlock named 'text2Sieger'
    text2Sieger = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text2Sieger"));
    // Get the Image named 'imageSieger'
    imageSieger = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"imageSieger"));
    // Get the Grid named 'gridWill'
    gridWill = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"gridWill"));
    // Get the Border named 'borderWill'
    borderWill = safe_cast<::Windows::UI::Xaml::Controls::Border^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"borderWill"));
    // Get the TextBlock named 'text1Will'
    text1Will = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text1Will"));
    // Get the TextBlock named 'text2Will'
    text2Will = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"text2Will"));
    // Get the Image named 'imageWill'
    imageWill = safe_cast<::Windows::UI::Xaml::Controls::Image^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"imageWill"));
    // Get the TextBlock named 'textÜberschrift'
    textÜberschrift = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"textÜberschrift"));
    // Get the Rectangle named 'rectÜberschrift'
    rectÜberschrift = safe_cast<::Windows::UI::Xaml::Shapes::Rectangle^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"rectÜberschrift"));
}

void ::Yatzy::Erfolge::Connect(int connectionId, Platform::Object^ target)
{
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

