

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class ListView;
                ref class ListViewItem;
                ref class TextBlock;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Shapes {
                ref class Rectangle;
            }
        }
    }
}

namespace Yatzy
{
    partial ref class Hilfe : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ LayoutRoot;
        private: ::Windows::UI::Xaml::Controls::ListView^ listText;
        private: ::Windows::UI::Xaml::Controls::ListViewItem^ listViewAusgabe;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlockBewertung;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlockAnleitung1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlockAnleitung2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlockWürfelkombination1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlockInfo1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlockInfo2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleEiner1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleEiner2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleZweier1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleZweier2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleDreier1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleDreier2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleVierer1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleVierer2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleFünfer1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleFünfer2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleSechser1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleSechser2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleBonus1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleBonus2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelle3erPasch1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelle3erPasch2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelle4erPasch1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelle4erPasch2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleklStraße1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleklStraße2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabellegrStraße1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabellegrStraße2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleFullHouse1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleFullHouse2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleChance1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleChance2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleYatzy1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ tabelleYatzy2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textÜberschrift;
        private: ::Windows::UI::Xaml::Shapes::Rectangle^ rectÜberschrift;
    };
}

