

//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"
#include "MainPage.xaml.h"




void ::Yatzy::MainPage::InitializeComponent()
{
    if (_contentLoaded)
        return;

    _contentLoaded = true;

    // Call LoadComponent on ms-appx:///MainPage.xaml
    ::Windows::UI::Xaml::Application::LoadComponent(this, ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml"), ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);

    // Get the ImageBrush named 'BrushKlassischWeiß1'
    BrushKlassischWeiß1 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushKlassischWeiß1"));
    // Get the ImageBrush named 'BrushKlassischWeiß2'
    BrushKlassischWeiß2 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushKlassischWeiß2"));
    // Get the ImageBrush named 'BrushKlassischWeiß3'
    BrushKlassischWeiß3 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushKlassischWeiß3"));
    // Get the ImageBrush named 'BrushKlassischWeiß4'
    BrushKlassischWeiß4 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushKlassischWeiß4"));
    // Get the ImageBrush named 'BrushKlassischWeiß5'
    BrushKlassischWeiß5 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushKlassischWeiß5"));
    // Get the ImageBrush named 'BrushKlassischWeiß6'
    BrushKlassischWeiß6 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushKlassischWeiß6"));
    // Get the ImageBrush named 'BrushKlassischGrau1'
    BrushKlassischGrau1 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushKlassischGrau1"));
    // Get the ImageBrush named 'BrushKlassischGrau2'
    BrushKlassischGrau2 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushKlassischGrau2"));
    // Get the ImageBrush named 'BrushKlassischGrau3'
    BrushKlassischGrau3 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushKlassischGrau3"));
    // Get the ImageBrush named 'BrushKlassischGrau4'
    BrushKlassischGrau4 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushKlassischGrau4"));
    // Get the ImageBrush named 'BrushKlassischGrau5'
    BrushKlassischGrau5 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushKlassischGrau5"));
    // Get the ImageBrush named 'BrushKlassischGrau6'
    BrushKlassischGrau6 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushKlassischGrau6"));
    // Get the ImageBrush named 'BrushModernWeiß1'
    BrushModernWeiß1 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushModernWeiß1"));
    // Get the ImageBrush named 'BrushModernWeiß2'
    BrushModernWeiß2 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushModernWeiß2"));
    // Get the ImageBrush named 'BrushModernWeiß3'
    BrushModernWeiß3 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushModernWeiß3"));
    // Get the ImageBrush named 'BrushModernWeiß4'
    BrushModernWeiß4 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushModernWeiß4"));
    // Get the ImageBrush named 'BrushModernWeiß5'
    BrushModernWeiß5 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushModernWeiß5"));
    // Get the ImageBrush named 'BrushModernWeiß6'
    BrushModernWeiß6 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushModernWeiß6"));
    // Get the ImageBrush named 'BrushModernGrau1'
    BrushModernGrau1 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushModernGrau1"));
    // Get the ImageBrush named 'BrushModernGrau2'
    BrushModernGrau2 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushModernGrau2"));
    // Get the ImageBrush named 'BrushModernGrau3'
    BrushModernGrau3 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushModernGrau3"));
    // Get the ImageBrush named 'BrushModernGrau4'
    BrushModernGrau4 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushModernGrau4"));
    // Get the ImageBrush named 'BrushModernGrau5'
    BrushModernGrau5 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushModernGrau5"));
    // Get the ImageBrush named 'BrushModernGrau6'
    BrushModernGrau6 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushModernGrau6"));
    // Get the ImageBrush named 'BrushRundWeiß1'
    BrushRundWeiß1 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRundWeiß1"));
    // Get the ImageBrush named 'BrushRundWeiß2'
    BrushRundWeiß2 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRundWeiß2"));
    // Get the ImageBrush named 'BrushRundWeiß3'
    BrushRundWeiß3 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRundWeiß3"));
    // Get the ImageBrush named 'BrushRundWeiß4'
    BrushRundWeiß4 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRundWeiß4"));
    // Get the ImageBrush named 'BrushRundWeiß5'
    BrushRundWeiß5 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRundWeiß5"));
    // Get the ImageBrush named 'BrushRundWeiß6'
    BrushRundWeiß6 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRundWeiß6"));
    // Get the ImageBrush named 'BrushRundGrau1'
    BrushRundGrau1 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRundGrau1"));
    // Get the ImageBrush named 'BrushRundGrau2'
    BrushRundGrau2 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRundGrau2"));
    // Get the ImageBrush named 'BrushRundGrau3'
    BrushRundGrau3 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRundGrau3"));
    // Get the ImageBrush named 'BrushRundGrau4'
    BrushRundGrau4 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRundGrau4"));
    // Get the ImageBrush named 'BrushRundGrau5'
    BrushRundGrau5 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRundGrau5"));
    // Get the ImageBrush named 'BrushRundGrau6'
    BrushRundGrau6 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRundGrau6"));
    // Get the ImageBrush named 'BrushNumerischWeiß1'
    BrushNumerischWeiß1 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushNumerischWeiß1"));
    // Get the ImageBrush named 'BrushNumerischWeiß2'
    BrushNumerischWeiß2 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushNumerischWeiß2"));
    // Get the ImageBrush named 'BrushNumerischWeiß3'
    BrushNumerischWeiß3 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushNumerischWeiß3"));
    // Get the ImageBrush named 'BrushNumerischWeiß4'
    BrushNumerischWeiß4 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushNumerischWeiß4"));
    // Get the ImageBrush named 'BrushNumerischWeiß5'
    BrushNumerischWeiß5 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushNumerischWeiß5"));
    // Get the ImageBrush named 'BrushNumerischWeiß6'
    BrushNumerischWeiß6 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushNumerischWeiß6"));
    // Get the ImageBrush named 'BrushNumerischGrau1'
    BrushNumerischGrau1 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushNumerischGrau1"));
    // Get the ImageBrush named 'BrushNumerischGrau2'
    BrushNumerischGrau2 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushNumerischGrau2"));
    // Get the ImageBrush named 'BrushNumerischGrau3'
    BrushNumerischGrau3 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushNumerischGrau3"));
    // Get the ImageBrush named 'BrushNumerischGrau4'
    BrushNumerischGrau4 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushNumerischGrau4"));
    // Get the ImageBrush named 'BrushNumerischGrau5'
    BrushNumerischGrau5 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushNumerischGrau5"));
    // Get the ImageBrush named 'BrushNumerischGrau6'
    BrushNumerischGrau6 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushNumerischGrau6"));
    // Get the ImageBrush named 'BrushBrailleWeiß1'
    BrushBrailleWeiß1 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushBrailleWeiß1"));
    // Get the ImageBrush named 'BrushBrailleWeiß2'
    BrushBrailleWeiß2 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushBrailleWeiß2"));
    // Get the ImageBrush named 'BrushBrailleWeiß3'
    BrushBrailleWeiß3 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushBrailleWeiß3"));
    // Get the ImageBrush named 'BrushBrailleWeiß4'
    BrushBrailleWeiß4 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushBrailleWeiß4"));
    // Get the ImageBrush named 'BrushBrailleWeiß5'
    BrushBrailleWeiß5 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushBrailleWeiß5"));
    // Get the ImageBrush named 'BrushBrailleWeiß6'
    BrushBrailleWeiß6 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushBrailleWeiß6"));
    // Get the ImageBrush named 'BrushBrailleGrau1'
    BrushBrailleGrau1 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushBrailleGrau1"));
    // Get the ImageBrush named 'BrushBrailleGrau2'
    BrushBrailleGrau2 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushBrailleGrau2"));
    // Get the ImageBrush named 'BrushBrailleGrau3'
    BrushBrailleGrau3 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushBrailleGrau3"));
    // Get the ImageBrush named 'BrushBrailleGrau4'
    BrushBrailleGrau4 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushBrailleGrau4"));
    // Get the ImageBrush named 'BrushBrailleGrau5'
    BrushBrailleGrau5 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushBrailleGrau5"));
    // Get the ImageBrush named 'BrushBrailleGrau6'
    BrushBrailleGrau6 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushBrailleGrau6"));
    // Get the ImageBrush named 'BrushJapanischWeiß1'
    BrushJapanischWeiß1 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushJapanischWeiß1"));
    // Get the ImageBrush named 'BrushJapanischWeiß2'
    BrushJapanischWeiß2 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushJapanischWeiß2"));
    // Get the ImageBrush named 'BrushJapanischWeiß3'
    BrushJapanischWeiß3 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushJapanischWeiß3"));
    // Get the ImageBrush named 'BrushJapanischWeiß4'
    BrushJapanischWeiß4 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushJapanischWeiß4"));
    // Get the ImageBrush named 'BrushJapanischWeiß5'
    BrushJapanischWeiß5 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushJapanischWeiß5"));
    // Get the ImageBrush named 'BrushJapanischWeiß6'
    BrushJapanischWeiß6 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushJapanischWeiß6"));
    // Get the ImageBrush named 'BrushJapanischGrau1'
    BrushJapanischGrau1 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushJapanischGrau1"));
    // Get the ImageBrush named 'BrushJapanischGrau2'
    BrushJapanischGrau2 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushJapanischGrau2"));
    // Get the ImageBrush named 'BrushJapanischGrau3'
    BrushJapanischGrau3 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushJapanischGrau3"));
    // Get the ImageBrush named 'BrushJapanischGrau4'
    BrushJapanischGrau4 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushJapanischGrau4"));
    // Get the ImageBrush named 'BrushJapanischGrau5'
    BrushJapanischGrau5 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushJapanischGrau5"));
    // Get the ImageBrush named 'BrushJapanischGrau6'
    BrushJapanischGrau6 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushJapanischGrau6"));
    // Get the ImageBrush named 'BrushRömischWeiß1'
    BrushRömischWeiß1 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRömischWeiß1"));
    // Get the ImageBrush named 'BrushRömischWeiß2'
    BrushRömischWeiß2 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRömischWeiß2"));
    // Get the ImageBrush named 'BrushRömischWeiß3'
    BrushRömischWeiß3 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRömischWeiß3"));
    // Get the ImageBrush named 'BrushRömischWeiß4'
    BrushRömischWeiß4 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRömischWeiß4"));
    // Get the ImageBrush named 'BrushRömischWeiß5'
    BrushRömischWeiß5 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRömischWeiß5"));
    // Get the ImageBrush named 'BrushRömischWeiß6'
    BrushRömischWeiß6 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRömischWeiß6"));
    // Get the ImageBrush named 'BrushRömischGrau1'
    BrushRömischGrau1 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRömischGrau1"));
    // Get the ImageBrush named 'BrushRömischGrau2'
    BrushRömischGrau2 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRömischGrau2"));
    // Get the ImageBrush named 'BrushRömischGrau3'
    BrushRömischGrau3 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRömischGrau3"));
    // Get the ImageBrush named 'BrushRömischGrau4'
    BrushRömischGrau4 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRömischGrau4"));
    // Get the ImageBrush named 'BrushRömischGrau5'
    BrushRömischGrau5 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRömischGrau5"));
    // Get the ImageBrush named 'BrushRömischGrau6'
    BrushRömischGrau6 = safe_cast<::Windows::UI::Xaml::Media::ImageBrush^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"BrushRömischGrau6"));
    // Get the ToggleButton named 'dice1'
    dice1 = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"dice1"));
    // Get the ToggleButton named 'dice2'
    dice2 = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"dice2"));
    // Get the ToggleButton named 'dice3'
    dice3 = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"dice3"));
    // Get the ToggleButton named 'dice4'
    dice4 = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"dice4"));
    // Get the ToggleButton named 'dice5'
    dice5 = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"dice5"));
    // Get the Button named 'controlButton'
    controlButton = safe_cast<::Windows::UI::Xaml::Controls::Button^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"controlButton"));
    // Get the TextBlock named 'pktEinerText'
    pktEinerText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktEinerText"));
    // Get the TextBlock named 'pktZweierText'
    pktZweierText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktZweierText"));
    // Get the TextBlock named 'pktDreierText'
    pktDreierText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktDreierText"));
    // Get the TextBlock named 'pktViererText'
    pktViererText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktViererText"));
    // Get the TextBlock named 'pktFünferText'
    pktFünferText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktFünferText"));
    // Get the TextBlock named 'pktSechserText'
    pktSechserText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktSechserText"));
    // Get the TextBlock named 'pktBonusText'
    pktBonusText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktBonusText"));
    // Get the TextBlock named 'pktSummeText'
    pktSummeText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktSummeText"));
    // Get the TextBlock named 'pkt3PaschText'
    pkt3PaschText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pkt3PaschText"));
    // Get the TextBlock named 'pkt4PaschText'
    pkt4PaschText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pkt4PaschText"));
    // Get the TextBlock named 'pktKlStraßeText'
    pktKlStraßeText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktKlStraßeText"));
    // Get the TextBlock named 'pktGrStraßeText'
    pktGrStraßeText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktGrStraßeText"));
    // Get the TextBlock named 'pktFullHouseText'
    pktFullHouseText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktFullHouseText"));
    // Get the TextBlock named 'pktChanceText'
    pktChanceText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktChanceText"));
    // Get the TextBlock named 'ptkYatzyText'
    ptkYatzyText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"ptkYatzyText"));
    // Get the TextBlock named 'pktGesamtText'
    pktGesamtText = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktGesamtText"));
    // Get the ToggleButton named 'pktEiner'
    pktEiner = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktEiner"));
    // Get the ToggleButton named 'pktZweier'
    pktZweier = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktZweier"));
    // Get the ToggleButton named 'pktDreier'
    pktDreier = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktDreier"));
    // Get the ToggleButton named 'pktVierer'
    pktVierer = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktVierer"));
    // Get the ToggleButton named 'pktFünfer'
    pktFünfer = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktFünfer"));
    // Get the ToggleButton named 'pktSechser'
    pktSechser = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktSechser"));
    // Get the TextBlock named 'pktBonus'
    pktBonus = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktBonus"));
    // Get the TextBlock named 'pktSumme'
    pktSumme = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktSumme"));
    // Get the ToggleButton named 'pkt3Pasch'
    pkt3Pasch = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pkt3Pasch"));
    // Get the ToggleButton named 'pkt4Pasch'
    pkt4Pasch = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pkt4Pasch"));
    // Get the ToggleButton named 'pktKlStraße'
    pktKlStraße = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktKlStraße"));
    // Get the ToggleButton named 'pktGrStraße'
    pktGrStraße = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktGrStraße"));
    // Get the ToggleButton named 'pktFullHouse'
    pktFullHouse = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktFullHouse"));
    // Get the ToggleButton named 'pktChance'
    pktChance = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktChance"));
    // Get the ToggleButton named 'pktYatzy'
    pktYatzy = safe_cast<::Windows::UI::Xaml::Controls::Primitives::ToggleButton^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktYatzy"));
    // Get the TextBlock named 'pktGesamt'
    pktGesamt = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(static_cast<Windows::UI::Xaml::IFrameworkElement^>(this)->FindName(L"pktGesamt"));
}

void ::Yatzy::MainPage::Connect(int connectionId, Platform::Object^ target)
{
    switch (connectionId)
    {
    case 1:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::AppBarButtonNeustart_Click);
        break;
    case 2:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::AppBarButtonErfolge_Click);
        break;
    case 3:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::AppBarButtonEinstellungen_Click);
        break;
    case 4:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::AppBarButtonPunkte_Click);
        break;
    case 5:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::AppBarButtonHilfe_Click);
        break;
    case 6:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::dice_Click);
        break;
    case 7:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::dice_Click);
        break;
    case 8:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::dice_Click);
        break;
    case 9:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::dice_Click);
        break;
    case 10:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::dice_Click);
        break;
    case 11:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::controlButton_Click);
        break;
    case 12:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::pkt_Click);
        break;
    case 13:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::pkt_Click);
        break;
    case 14:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::pkt_Click);
        break;
    case 15:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::pkt_Click);
        break;
    case 16:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::pkt_Click);
        break;
    case 17:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::pkt_Click);
        break;
    case 18:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::pkt_Click);
        break;
    case 19:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::pkt_Click);
        break;
    case 20:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::pkt_Click);
        break;
    case 21:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::pkt_Click);
        break;
    case 22:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::pkt_Click);
        break;
    case 23:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::pkt_Click);
        break;
    case 24:
        (safe_cast<::Windows::UI::Xaml::Controls::Primitives::ButtonBase^>(target))->Click +=
            ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::Yatzy::MainPage::*)(Platform::Object^, Windows::UI::Xaml::RoutedEventArgs^))&MainPage::pkt_Click);
        break;
    }
    (void)connectionId; // Unused parameter
    (void)target; // Unused parameter
    _contentLoaded = true;
}

