

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Media {
                ref class ImageBrush;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                namespace Primitives {
                    ref class ToggleButton;
                }
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Button;
                ref class TextBlock;
            }
        }
    }
}

namespace Yatzy
{
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushKlassischWeiß1;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushKlassischWeiß2;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushKlassischWeiß3;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushKlassischWeiß4;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushKlassischWeiß5;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushKlassischWeiß6;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushKlassischGrau1;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushKlassischGrau2;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushKlassischGrau3;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushKlassischGrau4;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushKlassischGrau5;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushKlassischGrau6;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushModernWeiß1;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushModernWeiß2;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushModernWeiß3;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushModernWeiß4;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushModernWeiß5;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushModernWeiß6;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushModernGrau1;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushModernGrau2;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushModernGrau3;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushModernGrau4;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushModernGrau5;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushModernGrau6;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRundWeiß1;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRundWeiß2;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRundWeiß3;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRundWeiß4;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRundWeiß5;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRundWeiß6;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRundGrau1;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRundGrau2;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRundGrau3;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRundGrau4;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRundGrau5;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRundGrau6;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushNumerischWeiß1;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushNumerischWeiß2;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushNumerischWeiß3;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushNumerischWeiß4;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushNumerischWeiß5;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushNumerischWeiß6;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushNumerischGrau1;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushNumerischGrau2;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushNumerischGrau3;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushNumerischGrau4;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushNumerischGrau5;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushNumerischGrau6;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushBrailleWeiß1;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushBrailleWeiß2;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushBrailleWeiß3;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushBrailleWeiß4;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushBrailleWeiß5;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushBrailleWeiß6;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushBrailleGrau1;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushBrailleGrau2;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushBrailleGrau3;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushBrailleGrau4;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushBrailleGrau5;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushBrailleGrau6;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushJapanischWeiß1;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushJapanischWeiß2;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushJapanischWeiß3;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushJapanischWeiß4;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushJapanischWeiß5;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushJapanischWeiß6;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushJapanischGrau1;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushJapanischGrau2;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushJapanischGrau3;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushJapanischGrau4;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushJapanischGrau5;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushJapanischGrau6;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRömischWeiß1;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRömischWeiß2;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRömischWeiß3;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRömischWeiß4;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRömischWeiß5;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRömischWeiß6;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRömischGrau1;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRömischGrau2;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRömischGrau3;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRömischGrau4;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRömischGrau5;
        private: ::Windows::UI::Xaml::Media::ImageBrush^ BrushRömischGrau6;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ dice1;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ dice2;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ dice3;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ dice4;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ dice5;
        private: ::Windows::UI::Xaml::Controls::Button^ controlButton;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktEinerText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktZweierText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktDreierText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktViererText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktFünferText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktSechserText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktBonusText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktSummeText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pkt3PaschText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pkt4PaschText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktKlStraßeText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktGrStraßeText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktFullHouseText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktChanceText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ptkYatzyText;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktGesamtText;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ pktEiner;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ pktZweier;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ pktDreier;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ pktVierer;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ pktFünfer;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ pktSechser;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktBonus;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktSumme;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ pkt3Pasch;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ pkt4Pasch;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ pktKlStraße;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ pktGrStraße;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ pktFullHouse;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ pktChance;
        private: ::Windows::UI::Xaml::Controls::Primitives::ToggleButton^ pktYatzy;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ pktGesamt;
    };
}

